name: Build Kernel CI

on:
  push:
    branches: [ "main" , "selinux" ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup environment 
      run: |
       sudo apt-get update && sudo apt-get install bc flex git ccache automake lzop bison gperf build-essential zip curl zlib1g-dev zlib1g-dev g++-multilib python3-networkx libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng -y
       sudo apt-get install git aptitude make gcc -y
       sudo apt install python-is-python3 build-essential openssl pip -y
       pip install virtualenv 
       export PATH=$PATH:$(pwd)/.local/bin
       sudo apt install openssl -y
       # install repo
       mkdir -p ~/.bin
       PATH="${pwd}/.bin:${PATH}"
       curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
       chmod a+rx ~/.bin/repo

    - name: set permissions
      run: sudo chmod +rwx *
      
    - name: run building script 
      run: bash ./build_kernel.sh
      
    - name: list fils
      run: |
        ls $(pwd)/arch/arm64/boot
      
    #- name: Upload to Release
    #  uses: softprops/action-gh-release@master
    #  with:
    #    files: |
    #      ouput/*
    #    name: Unofficial kernel for a137f // ${{ env.BUILD_DATE }}
    #    tag_name: ${{ github.run_id }}
    #    body: |
    #      Build: ${{ inputs.MANIFEST_BRANCH }}
    #      Device: a13ve
    #      Commit: see the repo - i hope it works

   
